---
title: "HOMEWORK #2"
author: '이상민'
date: '_April 9, 2020_'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Question
데이터셋을 이용하여 C5.0, randomForest의 accuracy를 비교하시오.

 - 10-fold cross validation으로 accuracy를 비교하시오 (seed=1234)
 
 - 각 classifier의 parameter 값은 default 값으로 한다
 
 - 각 모델의 민감도와 특이도를 보이시오

## Answer
```{r}
library(caret)
library(C50)
library(randomForest)
library(cvTools)
library(ROCR)

data("segmentationData")
dt <- segmentationData
```

### C5.0
```{r}
k <- 10
set.seed(1234)

folds <- cvFolds(nrow(dt), K=k)
acc <- c()
for (i in 1:k) {
    ts.idx <- folds$which == i
    ds.tr <- dt[-ts.idx, ]
    ds.ts <- dt[ts.idx, ]
    
    model <- C5.0(ds.tr[, -3], ds.tr$Class, trials=1, costs=NULL)
    pred <- predict(model, ds.ts, type="class")
    acc[i] <- mean(pred==ds.ts$Class)
}

acc_c5 <- mean(acc)
acc_c5

confusionMatrix(pred, ds.ts$Class)
```

### Random Forest
```{r}
k <- 10
set.seed(1234)

folds <- cvFolds(nrow(dt), K=k)
acc <- c()
for (i in 1:k) {
    ts.idx <- folds$which == i
    ds.tr <- dt[-ts.idx, ]
    ds.ts <- dt[ts.idx, ]
    
    model <- randomForest(Class~., data=ds.tr, na.action=na.omit)
    pred <- predict(model, ds.ts, type="class")
    acc[i] <- mean(pred==ds.ts$Class)
}

acc_rf <- mean(acc)
acc_rf

confusionMatrix(pred, ds.ts$Class)
```