---
title: "HOMEWORK #3"
author: '이상민'
date: '_April 16, 2020_'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question
위의 데이터셋을 이용하여 xgboost의 accuracy를 구하시오.

 - 10-fold cross validation으로 accuracy를 비교하시오 (seed=1234)
 
 - 각 classifier의 parameter 값은 default 값으로 한다
 
 - 각 모델의 민감도와 특이도를 보이시오
 
## Answer
```{r, message = FALSE, warning = FALSE}
library(caret)
library(cvTools)
library(xgboost)

data("segmentationData")
dt <- segmentationData
```

```{r}
k <- 10
set.seed(1234)

folds <- cvFolds(nrow(dt), K=k)
acc <- c()
sens <- c()
spec <- c()

for (i in 1:k) {
    ts.idx <- folds$which == i
    ds.tr <- dt[-ts.idx, ]
    ds.ts <- dt[ts.idx, ]
    lab.tr <- as.numeric(ds.tr$Class) - 1
    lab.ts <- as.numeric(ds.ts$Class) - 1
    
    mat.tr <- as.matrix(ds.tr[, -c(2, 3)])
    mat.ts <- as.matrix(ds.ts[, -c(2, 3)])
    
    model <- xgboost(mat.tr, label = lab.tr, max_depth = 6,
                     eta = 0.3, nround = 3, objective = "binary:logistic")
    pred <- predict(model, mat.ts)
    pred <- ifelse(pred > 0.5, 1, 0)
    pred <- as.factor(pred)
    lab.ts <- as.factor(lab.ts)
    
    res <- confusionMatrix(pred, lab.ts)
    acc[i] <- res$overall["Accuracy"]
    sens[i] <- res$byClass["Sensitivity"]
    spec[i] <- res$byClass["Specificity"]
}

res

tot_df <- data.frame(acc, sens, spec)
colnames(tot_df) <- c("Accuracy", "Sensitivity", "Specificity")
tot_df

mean_df <- data.frame(mean(acc), mean(sens), mean(spec))
colnames(mean_df) <- c("Accuracy", "Sensitivity", "Specificity")
mean_df
```

## Question
위의 데이터셋을 이용하여 knn, svm의 accuracy를 비교하되 caret 패키지를 이용하시오.

 - 10-fold cross validation으로 accuracy를 비교하시오 (seed=1234)
 
 - 각 classifier의 parameter 값은 default 값으로 한다
 
 - 각 모델의 민감도와 특이도를 보이시오
 
## Answer
### SVM
```{r} 
k <- 10
set.seed(1234)

folds <- cvFolds(nrow(dt), K=k)
acc <- c()
sens <- c()
spec <- c()

for (i in 1:k) {
    ts.idx <- folds$which == i
    ds.tr <- dt[-ts.idx, ]
    ds.ts <- dt[ts.idx, ]
    
    model <- train(Class~., ds.tr, method = "svmRadial")
    pred <- predict(model, ds.ts)
    
    res <- confusionMatrix(pred, ds.ts$Class)
    acc[i] <- res$overall["Accuracy"]
    sens[i] <- res$byClass["Sensitivity"]
    spec[i] <- res$byClass["Specificity"]
}

res

tot_df <- data.frame(acc, sens, spec)
colnames(tot_df) <- c("Accuracy", "Sensitivity", "Specificity")
tot_df

mean_df <- data.frame(mean(acc), mean(sens), mean(spec))
colnames(mean_df) <- c("Accuracy", "Sensitivity", "Specificity")
mean_df
```

### kNN
```{r}
k <- 10
set.seed(1234)

folds <- cvFolds(nrow(dt), K=k)
acc <- c()
sens <- c()
spec <- c()

for (i in 1:k) {
    ts.idx <- folds$which == i
    ds.tr <- dt[-ts.idx, ]
    ds.ts <- dt[ts.idx, ]
    
    model <- train(Class~., ds.tr, method = "knn")
    pred <- predict(model, ds.ts)
    
    res <- confusionMatrix(pred, ds.ts$Class)
    acc[i] <- res$overall["Accuracy"]
    sens[i] <- res$byClass["Sensitivity"]
    spec[i] <- res$byClass["Specificity"]
}

res

tot_df <- data.frame(acc, sens, spec)
colnames(tot_df) <- c("Accuracy", "Sensitivity", "Specificity")
tot_df

mean_df <- data.frame(mean(acc), mean(sens), mean(spec))
colnames(mean_df) <- c("Accuracy", "Sensitivity", "Specificity")
mean_df
```